### ISSUE TITLE
Sponsored posts not marked as sponsored on term archive pages

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-sponsors#191]
Noticed on Hyperallergic, this term archive page has a number of sponsored posts but they are not labelled as such: 

![sponsored-term-archive](https://user-images.githubusercontent.com/490703/173859861-7b586b59-230c-4fe9-91d8-f6006325d665.jpg)

For example this post: 

![sponsored-single](https://user-images.githubusercontent.com/490703/173859923-49868870-442e-447c-a500-3d154aa4f844.jpg)

We should make sure that sponsored posts are labeled appropriately anywhere they appear on the site including on archive pages.

**Comment by laurelfulford** [comment]
Hi @aschweigert! It looks like Hyperallergic rolled their own Sponsors solution, and is using a regular category and custom CSS rather than the Newspack Sponsors plugin -- the plugin isn't active on the site. 

I'm going to close this issue since it's not related to the plugin, but will follow up in Slack!
